package org.superbapps.integrations;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.junit.Assert;
import org.junit.jupiter.api.Test;
import org.superbapps.integrations.jira.dto.business.project.ProjectDto;
import org.superbapps.integrations.utils.JSONUtils;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

class JiraApplicationTests {

    String jsonResponseString
        //<editor-fold desc="json response from server">
        = "[\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10803\",\n"
        + "      \"id\":\"10803\",\n"
        + "      \"key\":\"BE\",\n"
        + "      \"name\":\"Brand Experience\",\n"
        + "      \"avatarUrls\":{ },\n"
        + "      \"projectCategory\":{ },\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   { },\n"
        + "   { },\n"
        + "   { },\n"
        + "   { },\n"
        + "   { },\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10406\",\n"
        + "      \"id\":\"10406\",\n"
        + "      \"key\":\"DEV\",\n"
        + "      \"name\":\"Development\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10406&avatarId=11575\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10406&avatarId=11575\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10406&avatarId=11575\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10406&avatarId=11575\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"software\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/11000\",\n"
        + "      \"id\":\"11000\",\n"
        + "      \"key\":\"HS\",\n"
        + "      \"name\":\"Hyperoptic Systems\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?avatarId=10324\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&avatarId=10324\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&avatarId=10324\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&avatarId=10324\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"software\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10804\",\n"
        + "      \"id\":\"10804\",\n"
        + "      \"key\":\"ILLA\",\n"
        + "      \"name\":\"ILLA\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10804&avatarId=10001\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10804&avatarId=10001\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10804&avatarId=10001\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10804&avatarId=10001\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10100\",\n"
        + "         \"id\":\"10100\",\n"
        + "         \"name\":\"Strategy\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"software\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10501\",\n"
        + "      \"id\":\"10501\",\n"
        + "      \"key\":\"IH\",\n"
        + "      \"name\":\"IT Helpdesk \",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10501&avatarId=10333\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10501&avatarId=10333\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10501&avatarId=10333\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10501&avatarId=10333\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10404\",\n"
        + "      \"id\":\"10404\",\n"
        + "      \"key\":\"II\",\n"
        + "      \"name\":\"IT Infrastructure\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10404&avatarId=10200\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10404&avatarId=10200\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10404&avatarId=10200\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10404&avatarId=10200\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10811\",\n"
        + "      \"id\":\"10811\",\n"
        + "      \"key\":\"NOC\",\n"
        + "      \"name\":\"NOC\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10811&avatarId=10325\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10811&avatarId=10325\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10811&avatarId=10325\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10811&avatarId=10325\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10204\",\n"
        + "         \"id\":\"10204\",\n"
        + "         \"name\":\"Networks\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10801\",\n"
        + "      \"id\":\"10801\",\n"
        + "      \"key\":\"PF\",\n"
        + "      \"name\":\"Portfolio\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10801&avatarId=10330\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10801&avatarId=10330\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10801&avatarId=10330\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10801&avatarId=10330\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10100\",\n"
        + "         \"id\":\"10100\",\n"
        + "         \"name\":\"Strategy\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10600\",\n"
        + "      \"id\":\"10600\",\n"
        + "      \"key\":\"PMO\",\n"
        + "      \"name\":\"Project Management\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10600&avatarId=10331\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10600&avatarId=10331\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10600&avatarId=10331\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10600&avatarId=10331\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10100\",\n"
        + "         \"id\":\"10100\",\n"
        + "         \"name\":\"Strategy\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10802\",\n"
        + "      \"id\":\"10802\",\n"
        + "      \"key\":\"QA\",\n"
        + "      \"name\":\"QA Automation\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?avatarId=10324\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&avatarId=10324\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&avatarId=10324\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&avatarId=10324\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"software\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10405\",\n"
        + "      \"id\":\"10405\",\n"
        + "      \"key\":\"RD\",\n"
        + "      \"name\":\"Reporting & Development\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10405&avatarId=10204\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10405&avatarId=10204\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10405&avatarId=10204\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10405&avatarId=10204\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10100\",\n"
        + "         \"id\":\"10100\",\n"
        + "         \"name\":\"Strategy\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10810\",\n"
        + "      \"id\":\"10810\",\n"
        + "      \"key\":\"SA\",\n"
        + "      \"name\":\"Sales Approvals\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10810&avatarId=10208\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10810&avatarId=10208\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10810&avatarId=10208\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10810&avatarId=10208\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10202\",\n"
        + "         \"id\":\"10202\",\n"
        + "         \"name\":\"Sales\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10808\",\n"
        + "      \"id\":\"10808\",\n"
        + "      \"key\":\"SSA\",\n"
        + "      \"name\":\"Sales Support Administration\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10808&avatarId=10330\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10808&avatarId=10330\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10808&avatarId=10330\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10808&avatarId=10330\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10202\",\n"
        + "         \"id\":\"10202\",\n"
        + "         \"name\":\"Sales\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10800\",\n"
        + "      \"id\":\"10800\",\n"
        + "      \"key\":\"SOLNS\",\n"
        + "      \"name\":\"Solutions\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10800&avatarId=10011\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10800&avatarId=10011\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10800&avatarId=10011\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10800&avatarId=10011\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10805\",\n"
        + "      \"id\":\"10805\",\n"
        + "      \"key\":\"TRL\",\n"
        + "      \"name\":\"Travel\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10805&avatarId=10211\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10805&avatarId=10211\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10805&avatarId=10211\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10805&avatarId=10211\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10201\",\n"
        + "         \"id\":\"10201\",\n"
        + "         \"name\":\"Operations\",\n"
        + "         \"description\":\"\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"service_desk\"\n"
        + "   \n"
        + "},\n"
        + "   {\n"
        + "      \"expand\":\"description,lead,url,projectKeys\",\n"
        + "      \"self\":\"https://jira-dev.superbapps.org/rest/api/2/project/10900\",\n"
        + "      \"id\":\"10900\",\n"
        + "      \"key\":\"OSS\",\n"
        + "      \"name\":\"Whalecloud\",\n"
        + "      \"avatarUrls\":{\n"
        + "         \"48x48\":\"https://jira-dev.superbapps.org/secure/projectavatar?pid=10900&avatarId=10208\",\n"
        + "         \"24x24\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=small&pid=10900&avatarId=10208\",\n"
        + "         \"16x16\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=xsmall&pid=10900&avatarId=10208\",\n"
        + "         \"32x32\":\"https://jira-dev.superbapps.org/secure/projectavatar?size=medium&pid=10900&avatarId=10208\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectCategory\":{\n"
        + "         \"self\":\"https://jira-dev.superbapps.org/rest/api/2/projectCategory/10000\",\n"
        + "         \"id\":\"10000\",\n"
        + "         \"name\":\"Systems\",\n"
        + "         \"description\":\"Used to group all the Systems departmental JIRA projects\"\n"
        + "      \n"
        + "},\n"
        + "      \"projectTypeKey\":\"software\"\n"
        + "   \n"
        + "}\n"
        + "]";
    //</editor-fold>

    private List<ProjectDto> parsed() {
        Type projectListType = new TypeToken<ArrayList<ProjectDto>>() {
        }.getType();
        return new Gson().fromJson(jsonResponseString, projectListType);
    }

    @Test
    void test_ListOfProjects_With_Gson() {
        List<ProjectDto> result = parsed();
        Assert.assertEquals(21L, result.size());
    }

    @Test
    void test_ListOfProjects_With_JSONUtils() {
        List<ProjectDto> result = JSONUtils.parseResponseAsList(jsonResponseString, ProjectDto.class);
        Assert.assertEquals(21L, result.size());
    }

    @Test
    void test_Equal_ListsOfProjects() {
        List<ProjectDto> expexted = parsed();
        List<ProjectDto> result = JSONUtils.parseResponseAsList(jsonResponseString, ProjectDto.class);

        for (int i = 0; i < result.size(); i++) {
            if (!result.get(i).equals(expexted.get(i)))
                throw new RuntimeException("Not equal");
        }
    }

}
